<?php

namespace ZnLib\Components\Http\Enums;

/**
 * Имена ключей массива $_SERVER
 */
class HttpServerEnum
{

    const HTTP_ORIGIN = 'HTTP_ORIGIN';
    const HTTP_ACCESS_CONTROL_REQUEST_HEADERS = 'HTTP_ACCESS_CONTROL_REQUEST_HEADERS';
    const HTTP_ACCESS_CONTROL_REQUEST_METHOD = 'HTTP_ACCESS_CONTROL_REQUEST_METHOD';

    const REDIRECT_STATUS = 'REDIRECT_STATUS';
    const HTTP_HOST = 'HTTP_HOST';
    const HTTP_USER_AGENT = 'HTTP_USER_AGENT';
    const HTTP_ACCEPT = 'HTTP_ACCEPT';
    const HTTP_ACCEPT_LANGUAGE = 'HTTP_ACCEPT_LANGUAGE';
    const HTTP_ACCEPT_ENCODING = 'HTTP_ACCEPT_ENCODING';
    const HTTP_REFERER = 'HTTP_REFERER';
    const HTTP_CONNECTION = 'HTTP_CONNECTION';
    const HTTP_COOKIE = 'HTTP_COOKIE';
    const HTTP_UPGRADE_INSECURE_REQUESTS = 'HTTP_UPGRADE_INSECURE_REQUESTS';
    const HTTP_CACHE_CONTROL = 'HTTP_CACHE_CONTROL';
    
    const PATH = 'PATH';
    const SYSTEM_ROOT = 'SystemRoot';
    const COMSPEC = 'COMSPEC';
    const PATHEXT = 'PATHEXT';
    const WINDIR = 'WINDIR';
    const SERVER_SIGNATURE = 'SERVER_SIGNATURE';
    const SERVER_SOFTWARE = 'SERVER_SOFTWARE';
    const SERVER_NAME = 'SERVER_NAME';
    const SERVER_ADDR = 'SERVER_ADDR';
    const SERVER_PORT = 'SERVER_PORT';
    const REMOTE_ADDR = 'REMOTE_ADDR';
    const DOCUMENT_ROOT = 'DOCUMENT_ROOT';
    const REQUEST_SCHEME = 'REQUEST_SCHEME';
    const CONTEXT_PREFIX = 'CONTEXT_PREFIX';
    const CONTEXT_DOCUMENT_ROOT = 'CONTEXT_DOCUMENT_ROOT';
    const SERVER_ADMIN = 'SERVER_ADMIN';
    const SCRIPT_FILENAME = 'SCRIPT_FILENAME';
    const REMOTE_PORT = 'REMOTE_PORT';
    const REDIRECT_URL = 'REDIRECT_URL';
    const GATEWAY_INTERFACE = 'GATEWAY_INTERFACE';
    const SERVER_PROTOCOL = 'SERVER_PROTOCOL';
    const REQUEST_METHOD = 'REQUEST_METHOD';
    const QUERY_STRING = 'QUERY_STRING';
    const REQUEST_URI = 'REQUEST_URI';
    const SCRIPT_NAME = 'SCRIPT_NAME';
    const PHP_SELF = 'PHP_SELF';
    const REQUEST_TIME_FLOAT = 'REQUEST_TIME_FLOAT';
    const REQUEST_TIME = 'REQUEST_TIME';
    const ARGV = 'argv';
    const ARGC = 'argc';

}
